# NumPy Arrays

In [3]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [13]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
np.ones(4)


array([ 1.,  1.,  1.,  1.])

In [15]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [16]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [17]:
np.eye(4)


array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [19]:
np.random.rand(5)

array([ 0.32704412,  0.26685115,  0.12286309,  0.75977804,  0.06977716])

In [22]:
np.random.rand(2,5)

array([[ 0.5898549 ,  0.88081432,  0.76955468,  0.94165997,  0.97173016],
       [ 0.51998701,  0.29127716,  0.96706587,  0.59411925,  0.02814422]])

In [23]:
np.random.randn(2)

array([ 1.24836923, -1.53806933])

In [30]:
np.random.randint(1,100,10)

array([97, 40, 52, 15, 92, 69, 53, 10, 38, 32])

In [35]:
arr = np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0,50,10)
ranarr

array([24, 39, 37, 35, 27, 25, 26, 15, 17, 46])

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr.max()

46

In [42]:
ranarr.min()

15

Index of an array's max and min value:

In [43]:
ranarr.argmax()

9

In [44]:
ranarr.argmin()

7

In [45]:
arr.shape

(25,)

In [46]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [47]:
arr.dtype


dtype('int64')

In [48]:
from numpy.random import randint

In [49]:
randint(2,10)


6