# NumPy Indexing and Selection 

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

NumPy Array Broadcasting (NumPy advantages)

In [9]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr = np.arange(0,11)
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

NumPy arrays aren't copied, but referenced

In [15]:
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)


[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

To copy an array:

In [17]:
arr_copy = arr.copy()
arr_copy[:] = 100
print(arr)
print(arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10]
[100 100 100 100 100 100 100 100 100 100 100]


# Indexing a matrix

In [20]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
arr_2d[0]

array([ 5, 10, 15])

In [22]:
arr_2d[1][1]

25

In [24]:
arr_2d[1,1]

25

In [25]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [31]:
arr_2d[0:,2:]

array([[15],
       [30],
       [45]])

In [34]:
arr_2d[1,1:]

array([25, 30])

# Condictional Selection

In [36]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [41]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr>7]

array([ 8,  9, 10])

Exercise

In [43]:
array2d = np.arange(50).reshape(5,10)

In [49]:
x = array2d[1:3,3:5]
x

array([[13, 14],
       [23, 24]])

In [50]:
x[x%2==0]

array([14, 24])